version: '3.9'
services:
    web:
        build: ./php-apache
        restart: always
        volumes:
            - ./laravel-graphql:/var/www/html
        ports:
            - 80:80
        depends_on: 
            - mysql
    mysql:
        image: mysql:8
        restart: always
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports: 
            - 3306:3306
        volumes:
            - bbs-db:/usr/lib/msyql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: mylaravel
            MYSQL_USER_PASSWORD: password
    mail:
        image: mailhog/mailhog
        ports:
            - 8025:8025
volumes:
    bbs-db: